# Generated by Django 5.0.6 on 2026-06-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('guests', models.PositiveIntegerField(default=2, verbose_name='Кількість гостей')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Час')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Підтверджено')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показу')),
            ],
            options={
                'verbose_name': 'Категорія меню',
                'verbose_name_plural': 'Категорії меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва страви')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото страви')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для замовлення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показу')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
