# Generated by Django 5.0.6 on 2026-06-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
    ]
